# 用户设置
# 学号:
#   pwd：密码
#   CurSheng: 当前所在省
#   CurShi: 当前所在市
#   CurXian: 当前所在县/区
#   Detail: 详细地址
# 注意引号
"00000000":
  pwd: "00000"
  CurSheng: "浙江"
  CurShi: "杭州市"
  CurXian: ""
  Detail: ""
"11111111":
  pwd: "000000"
  CurSheng: "浙江"
  CurShi: "嘉兴市"
  CurXian: ""
  Detail: ""