# 用户设置
# 学号:
#   pwd：密码
#   CurSheng: 当前所在省
#   CurShi: 当前所在市
#   CurXian: 当前所在县/区
#   Detail: 详细地址
# 注意引号
"19721717":
  pwd: "Zx000000"
  CurSheng: "湖北"
  CurShi: "黄冈市"
  CurXian: "浠水县"
  Detail: "散花镇马垅街"